---

- name: disable ipv6 by write sysctl option 1
  command: "echo 'net.ipv6.conf.all.disable_ipv6 = 1' >> /etc/sysctl.conf"
  become: yes

- name: disable ipv6 by write sysctl option 1
  command: "echo 'net.ipv6.conf.default.disable_ipv6 = 1' >> /etc/sysctl.conf"
  become: yes

- name: disable ipv6 by enable sysctl options
  command: "sysctl -p"
  become: yes

- name: add user with ghost home dir
  ansible.builtin.user:
    name: "{{GHOST_UNIX_USER}}"
    password: "{{GHOST_UNIX_PASSWORD | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string)}}"
    state: present
    group: sudo
    home: "{{GHOST_HOME}}"
  become: yes

# https://docs.ansible.com/ansible/latest/collections/community/mysql/mysql_user_module.html#ansible-collections-community-mysql-mysql-user-module

- name: Set password of root user
  mysql_user:
    name: "{{GHOST_DB_ROOT_USER}}"
    password: "{{GHOST_DB_ROOT_PASSWORD}}"
    password_expire: never
  become: yes

- name: add ghost database
  mysql_db:
    name: "{{GHOST_DB_NAME}}"
    state: presen
  become: yes

- name: add mysql user
  mysql_user:
    name: "{{GHOST_DB_USER}}"
    password: "{{GHOST_DB_PASSWORD}}"
    password_expire: never
    priv: "{{GHOST_DB_NAME}}:ALL"
  become: yes

- name: install ghost to ghost home
  command: "ghost install {{GHOST_VERSION}} --ip '::' --url={{GHOST_PROJECT_URL}} --port={{GHOST_PORT}} --db={{GHOST_DB_HOST}} --dbhost=localhost --dbport={{GHOST_DB_PORT}} --dbuser={{GHOST_DB_USER}} --dbpass={{GHOST_DB_PASSWORD}} --dbname={{GHOST_DB_NAME}} --no-setup-ssl --no-prompt --start"}
  # command: "ghost install --ip={{ansible_default_ipv4.address}} --url={{GHOST_PROJECT_URL}} --db={{GHOST_DB_HOST}} --dbhost=localhost --dbport={{GHOST_DB_PORT}} --dbuser={{GHOST_DB_USER}} --dbpass={{GHOST_DB_PASSWORD}} --dbname={{GHOST_DB_NAME}} --no-prompt --start"}
  # command: "ghost install --url={{GHOST_PROJECT_URL}} --db={{GHOST_DB}} --dbhost={{GHOST_DB_HOST}} --dbuser={{GHOST_DB_USER}} --dbpass={{GHOST_DB_PASSWORD}} --dbname={{GHOST_DB_NAME}} --mail={{GHOST_SMTP}} --mailservice={{GHOST_SMTP_SERVICE}} --mailuser={{GHOST_SMTP_USER}} --mailpass={{GHOST_SMTP_PASSWORD}} --mailport={{GHOST_SMTP_PORT}} --sslemail={{GHOST_LETSENCRYPT_USER}} --no-setup-ssl --no-prompt --start"
  become: yes
  become_user: "{{GHOST_UNIX_USER}}"
  become_password: "{{GHOST_UNIX_PASSWORD}}"
