---

NODE_MAJOR: 18
GHOST_HOME: "/var/lib/ghost-home"
GHOST_UNIX_USER: "ghost"
GHOST_UNIX_PASSWORD: "ghost"
GHOST_ADMIN_USER: "ghost"
GHOST_ADMIN_PASSWORD: "atleast10chars"
GHOST_ADMIN_EMAIL: "ghost@example.com"
GHOST_PROJECT_URL: "http://ghost-cms.internal"
GHOST_PORT: "2368"
GHOST_DB_HOST: "mysql"
GHOST_DB_PORT: "mysql"
GHOST_DB_ROOT_USER: "root"
GHOST_DB_ROOT_PASSWORD: ""
GHOST_DB_USER: "ghost"
GHOST_DB_PASSWORD: "ghost"
GHOST_DB_NAME: "ghostdb"
GHOST_VERSION: "5.87.3"
# GHOST_SMTP: 
# GHOST_SMTP_SERVICE: 
# GHOST_SMTP_USER: 
# GHOST_SMTP_PASSWORD: 
# GHOST_SMTP_PORT: 
# GHOST_LETSENCRYPT_USER: 
